In [81]:
from scipy.io import arff
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.model_selection import StratifiedShuffleSplit

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

def which_arff_dataset(dataset, n_splits=5):

    data = arff.loadarff('../ALIH/datasets/' + dataset)
    data = pd.DataFrame(data[0])
    
    #TODOS OS DATASETS SÃO DE CLASSIFICAÇÃO? Se não, o list [:-1] pode dar ruim
    columnTransformer = ColumnTransformer([('encoder',
                                            OneHotEncoder(),
                                            list(data.select_dtypes(include=['object']).columns)[:-1])],
                                          remainder='passthrough')
    
    data = pd.DataFrame(columnTransformer.fit_transform(data))

    X_raw = data[data.columns[:-1]].to_numpy()
    y_raw = data[data.columns[-1]].to_numpy()

    # pq o y sem o enconding não funciona?
    ley = LabelEncoder()
    ley.fit(y_raw)
    y_raw = ley.transform(y_raw)

    # cross validation bags
    data_cv = StratifiedShuffleSplit(n_splits=n_splits, train_size=0.2, random_state=0)  # n_splits
    data_cv.get_n_splits(X_raw, y_raw)

    # extraindo ids do data_cv
    idx_data = []
    for train_index, test_index in data_cv.split(X_raw, y_raw):
        idx_data.append([train_index, test_index])

    return X_raw, y_raw, idx_data, dataset

In [82]:
datasets = ['1496_ringnorm.arff','1116_musk.arff']

In [87]:
X_raw, y_raw, idx_data, dataset = which_arff_dataset(datasets[1])

In [88]:
print(X_raw, y_raw, idx_data, dataset)

[[1.0 0.0 0.0 ... -50.0 -112.0 96.0]
 [1.0 0.0 0.0 ... -61.0 -136.0 79.0]
 [1.0 0.0 0.0 ... -67.0 -145.0 39.0]
 ...
 [0.0 0.0 0.0 ... -66.0 -144.0 -6.0]
 [0.0 0.0 0.0 ... -44.0 -116.0 117.0]
 [0.0 0.0 0.0 ... -44.0 -115.0 118.0]] [1 1 1 ... 0 0 0] [[array([5384, 5885, 2999, ..., 3648, 6389, 1171]), array([6079, 5537,  188, ..., 4054, 4742, 5742])], [array([1285, 2338, 3469, ...,  793, 5448, 1454]), array([1747, 5461, 2062, ..., 5296, 6519, 4546])], [array([1391, 1338, 2472, ..., 5392, 5848, 4913]), array([  10, 1980, 4923, ..., 5378, 5268, 2786])], [array([5939,  300,  982, ..., 2366, 3733, 2699]), array([2046, 2239, 1569, ..., 3977,  132, 3895])], [array([5533, 1661, 3342, ..., 4445, 5519, 6536]), array([3685, 3122, 2099, ..., 2735, 2016, 4057])]] 1116_musk.arff


In [79]:
#data.info()
list(data.select_dtypes(include=['object']).columns)[:-1]

['molecule_name']

In [71]:
columnTransformer = ColumnTransformer([('encoder',
                                        OneHotEncoder(),
                                        list(data.select_dtypes(include=['object']).columns)[:-1])],
                                      remainder='passthrough')
  
data = pd.DataFrame(columnTransformer.fit_transform(data))

In [73]:
data.shape

(6598, 269)